#!python3
#An insecure password locker program

PASSWORDS={'email':'eriKINF5251fsfffrf',
           'blog':'DFFfe516325frfsgrGDDDF',
           'luggage':'12345'}

import sys
import pyperclip

if len(sys.argv) < 2:
    print('Usage:python password_manage.py [account] - copy account password')
    sys.exit()

account=sys.argv[1] # first command line arg is the account name

if account in PASSWORDS:
    pyperclip.copy(PASSWORDS[account])
    print('password for '+account+' copied to clipboard.')
else:
    print('There is no account named '+account)
    
